### ISSUE TITLE
PA Review: User Authentication

### ISSUE THREAD

**Issue by niartenyaw** [appacademy/bluebird#20]
- [ ] Backend: DB, model, controller, views
- [ ] Redux Loop: ajax, actions, reducer
- [ ] Presentational Components
- [ ] Styling
  - [ ] When errors are displayed, the form adjusts properly (input boxes move up, sign in/sign up button moves down, and errors are displayed in between)
- [ ] Smooth, bug free navigation
  - [ ] Login errors clears when switching from login form to sign up form (and vice-versa)
  - [ ] Going to a random route `/#/oweiniouewbrviuwebv` should redirect to either `/`, `/login`, or `/signup`
  - [ ] Errors should display for both `/signup` and`/login`.
  - [ ] Errors should clear when moving between `/signup` and `/login`.
- [ ] Adequate and appropriate seeds
  - [ ] Demo Login Works

**Comment by andywynkoop** [comment]
- [x] You don't render errors
- [x] Your styling looks bad

**Comment by niartenyaw** [comment]
![](https://proxy.duckduckgo.com/iu/?u=https%3A%2F%2Fwww.futuro.cl%2Fwp-content%2Fuploads%2F2018%2F11%2Fpikachu-web-590x340.jpg&f=1)

**Comment by andywynkoop** [comment]
You're on the projector now

**Comment by niartenyaw** [comment]
![](https://proxy.duckduckgo.com/iu/?u=https%3A%2F%2Fs3.amazonaws.com%2Frails-camp-tutorials%2Fblog%2Fprogramming%2Bmemes%2Fprogramming-or-googling.jpg&f=1)

**Comment by niartenyaw** [comment]
![](https://proxy.duckduckgo.com/iu/?u=https%3A%2F%2Fpics.me.me%2Fwho-would-win-a-computer-program-with-one-curly-boy-21638195.png&f=1)
